fallback to og image if no images
hackclub/scrappy pull request #519
Opened 2023-12-22 12:01 UTC by JosiasAurel

addresses #380

2023-12-22 13:42 UTC, grymmy commented on src/app.js
> +// app.message(subtype("file_share"), execute(create));
please add commentary on why these things are disabled - or delete them entirely

2023-12-22 13:44 UTC, grymmy commented on src/lib/updates.js
> +      app.client.chat.delete({
add comment explaining what this does

2023-12-22 13:44 UTC, grymmy commented on src/lib/updates.js
> +      postEphemeral(channel, t("messages.delete", { text }), user)
add comment explaining

2023-12-22 13:45 UTC, grymmy commented on src/lib/utils.js
> +  const matcher = /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()'@:%_\+.~#?!&//=]*)/gi;
describe at high level what this regex does, if it conforms to a standard, does it support https vs http, etc

2023-12-22 13:52 UTC, grymmy requested changes

2023-12-22 13:52 UTC, grymmy commented on src/events/reactionAdded.js
>        if (!message.files || message.files.length == 0) {
This is just a general rule of mine - when I see two lines in a conditional that nearly match such as what is contained here, I usually extract the difference into a variable and then condense the code to one call.  For instance, you could refactor this to:

```
let hasNoFiles = !message.files || message.files.length == 0
let files = hasNoFiles ? [] : message.files
let update = await createUpdate(files, channel, ts, user, message.text)
```

I would argue ^ is more readable & concise, also doesn't require the predefined-and-then-mutated variable 'update'

2023-12-22 14:09 UTC, grymmy commented on src/lib/updates.js
> +    for (const url of urls) {
nit - could this be parallelized, or is it truly order dependent?

2023-12-22 14:10 UTC, grymmy approved these changes

2023-12-22 14:15 UTC, merged

2023-12-25 21:40 UTC, MatthewStanciu commented
Woah cool!!! Thanks for doing this!